<?php

namespace logic\Attachment\Validation;

use logic\user\model\User;

/**
 * 获取一个集合的索引
 * Class get_array_index
 * @package apps\main\upload
 */
class get_array_index extends \core\CoreValidation
{

    protected function initialize()
    {
        # 验证 user_id
        $this->add_exist('user_id', [
            'class_name_list' => User::class,
            'message' => 'exist'
        ]);
        # 验证备注
        $this->add_required('remark', [
            'message' => 'required'
        ]);
        $this->add_stringLength('remark', [
            'message' => 'stringLength',
            'max' => 100,
            'min' => 1
        ]);

        # 验证单一文件性质
        $this->add_in('only', [
            'message' => 'in',
            'domain' => [
                1, 0
            ]
        ]);
        return parent::initialize(); // TODO: Change the autogenerated stub
    }
}